name            = "pywatt_module_template"
version         = "0.1.0"
compatible_core = ">=1.0.0, <2.0.0"
executable      = "pywatt_module_template"
transport       = "http"

# Environment variables the orchestrator must inject
env = ["DATABASE_URL", "REDIS_URL"]

[endpoints."/api/hello"]
methods  = ["GET"]
auth     = "none"
timeout  = "30s"

[endpoints."/health"]
methods  = ["GET"]
auth     = "none"
timeout  = "5s"

[endpoints."/metrics"]
methods  = ["GET"]
auth     = "none"
timeout  = "10s"

[endpoints."/ping"]
methods  = ["GET"]
auth     = "none"
timeout  = "5s"
