name: pywatt-sdk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pydantic>=2.0.0
  - typing-extensions>=4.0.0
  - structlog>=23.1.0
  - python-dotenv>=1.0.0
  - httpx>=0.24.0
  - websockets>=11.0.0
  - orjson>=3.8.0
  - cryptography>=41.0.0
  - pyjwt>=2.8.0
  - msgpack>=1.0.7
  - pytest>=7.0.0
  - pytest-asyncio>=0.21.0
  - pytest-mock>=3.11.0
  - black>=23.0.0
  - isort>=5.12.0
  - mypy>=1.4.0
  - pip 