name: Python SDK Conda CI

on:
  push:
    paths:
      - 'python_sdk/**'
  pull_request:
    paths:
      - 'python_sdk/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: python_sdk/environment.yml
          activate-environment: pywatt-sdk
          use-mamba: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: flexible
          show-channel-urls: true
      - name: Install Python SDK
        working-directory: python_sdk
        shell: bash -l {0}
        run: |
          conda info
          conda list
          pip install . --no-deps
      - name: Run tests
        working-directory: python_sdk
        shell: bash -l {0}
        run: |
          pytest 